# -*- coding: utf-8 -*-
"""Python-examples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3I50KVZSHK9Itepor3qegiTjhw2inwo
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv("/content/drive/My Drive/student.csv")

df = df.rename(columns={"mark": "score"})
print(df)

df = df.drop(columns=["passed"])
print(df)

print(df[df["class"]=="Four"])

import pandas as pd

df = pd.read_csv("/content/drive/My Drive/student.csv")

df = df.rename(columns={"mark": "score"})

df["grade"] = ["A" if x >= 86 else ("B" if x >= 70 else ("C" if x >= 60 else "D")) for x in df["score"]]
print(df)

x = df.sort_values(by="score", ascending=False)
print(x)

df.describe()

df["name"]

x = df[["name", "mark"]]
print(x)

df.info()

display(df.head(5))